public class LevelConfig {
    public static final String[][][] LEVEL_1_DATA = {
            {{"NORMAL"}, null, null, null, null},
        {null, {"NORMAL"}, null, {"NORMAL"}, null},
        {{"NORMAL"}, null, {"NORMAL"}, null, {"NORMAL"}},
        
        {null, {"NORMAL", "NORMAL"}, null, {"NORMAL"}, null},
        {{"CONEHEAD"}, {"NORMAL"}, {"CONEHEAD"}, {"NORMAL"}, {"CONEHEAD"}},
    
        {{"NORMAL", "NORMAL"}, {"CONEHEAD"}, null, {"CONEHEAD"}, {"NORMAL"}},
        {{"CONEHEAD"}, {"CONEHEAD"}, {"CONEHEAD"}, {"CONEHEAD"}, {"CONEHEAD"}},
        {{"BUCKETHEAD"}, {"CONEHEAD"}, {"BUCKETHEAD"}, {"CONEHEAD"}, {"BUCKETHEAD"}},
    
        {{"BUCKETHEAD"}, null, {"BUCKETHEAD"}, null, {"BUCKETHEAD"}},
        
        {{"CONEHEAD", "CONEHEAD"}, {"BUCKETHEAD"}, {"CONEHEAD", "CONEHEAD"}, {"BUCKETHEAD"}, {"CONEHEAD"}},
        {{"BUCKETHEAD"}, {"BUCKETHEAD"}, {"NORMAL"}, {"BUCKETHEAD"}, {"BUCKETHEAD"}},
        {{"BRICKHEAD"}, {"BUCKETHEAD"}, {"BUCKETHEAD"}, {"BUCKETHEAD"}, {"BRICKHEAD"}},
        
        {
            {"BRICKHEAD"}, 
            {"BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD"}, 
            null, 
            {"BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD"}, 
            {"BRICKHEAD"}
        },
    
        {
            {"NORMAL", "CONEHEAD", "BUCKETHEAD", "NORMAL", "CONEHEAD", "BUCKETHEAD", "BRICKHEAD"}, 
            {"NORMAL", "CONEHEAD"}, 
            {"CONEHEAD", "CONEHEAD", "NORMAL", "NORMAL", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD"}, 
            {"NORMAL", "CONEHEAD"}, 
            {"NORMAL", "NORMAL", "CONEHEAD", "CONEHEAD", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD"}
        },
    
        {
            {"BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BUCKETHEAD"}, 
            {"BUCKETHEAD", "BRICKHEAD"}, 
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "NORMAL"}, 
            {"BUCKETHEAD", "BUCKETHEAD", "BUCKETHEAD", "CONEHEAD", "BRICKHEAD"}, 
            {"BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BUCKETHEAD"}
        },
    
        {
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "CONEHEAD"}, 
            {"BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD"}, 
             null, 
            {"BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD"}, 
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "CONEHEAD"}
        },
    
        {
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"}, 
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"}, 
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"}, 
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"}, 
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"}
        },
        
        {
            {"NORMAL", "BRICKHEAD", "BRICKHEAD", "NORMAL", "NORMAL", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"},
            {"BRICKHEAD", "CONEHEAD", "BRICKHEAD", "CONEHEAD", "BRICKHEAD", "CONEHEAD", "BRICKHEAD", "CONEHEAD", "BRICKHEAD"},
            {"NORMAL", "BRICKHEAD", "NORMAL", "BRICKHEAD", "NORMAL", "BRICKHEAD", "NORMAL", "BRICKHEAD", "NORMAL"},
            {"BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD"},
            {"CONEHEAD", "BUCKETHEAD", "BRICKHEAD", "NORMAL", "CONEHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"}
        },
        
        {
            {"BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD"},
            {"BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BUCKETHEAD"},
            {"BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"},
            {"BUCKETHEAD", "BUCKETHEAD", "BUCKETHEAD", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"},
            {"BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BUCKETHEAD", "BRICKHEAD", "BUCKETHEAD"}
        },
        {
            {"NORMAL", "NORMAL", "BRICKHEAD", "BRICKHEAD", "NORMAL", "NORMAL", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"},
            {"CONEHEAD", "BRICKHEAD", "CONEHEAD", "BRICKHEAD", "CONEHEAD", "BRICKHEAD", "CONEHEAD", "BRICKHEAD", "CONEHEAD", "BRICKHEAD"},
            {"BRICKHEAD", "NORMAL", "BRICKHEAD", "NORMAL", "BRICKHEAD", "NORMAL", "BRICKHEAD", "NORMAL", "BRICKHEAD", "NORMAL"},
            {"BUCKETHEAD", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD", "BUCKETHEAD", "BUCKETHEAD", "BUCKETHEAD", "BRICKHEAD"},
            {"NORMAL", "CONEHEAD", "BUCKETHEAD", "BRICKHEAD", "NORMAL", "CONEHEAD", "BUCKETHEAD", "BRICKHEAD", "BRICKHEAD", "BRICKHEAD"}
        }
    };
}